name: RCCommons
main: de.raidcraft.commons.RCCommonsPlugin
version: ${project.version}#${build.number}
author: Silthus
website: www.raid-craft.de
depend: [RaidCraft-API]
database: true
api-version: 1.13